routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('categories', CategoryController::class)->except(['show']);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'id',
        'name',
        'is_publish'
    ];
}

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Traits\JsonResponse;
use App\Services\Contracts\CategoryInterface as CategoryService;
use App\Http\Resources\CategoryResource;
use App\Http\Requests\Api\CategoryRequest;

class CategoryController extends Controller
{
    use JsonResponse;

    protected $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try {
            $categories = $this->categoryService->getAllSimplePaginatedWithParams($request);
            return $this->sendResponse(CategoryResource::collection($categories), 'list of all categories', 200);

        } catch(\Exception $e) {
            return $this->sendError($e->getMessage());
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        try {
            $category = $this->categoryService->create($request);
            return $this->sendResponse(new CategoryResource($category), 'category created successfully', 201);

        } catch(\Exception $e) {
            return $this->sendError($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            if(!$this->categoryService->find($id)) {
                return $this->sendError('category data not found', 404);
            }

            return $this->sendResponse(new CategoryResource($this->categoryService->find($id)), 'category details');

        } catch(\Exception $e) {
            return $this->sendError($e->getMessage());
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) 
    {
       try {
            if(!$this->categoryService->find($id)) {
                return $this->sendError('category data not found', 404);
            }
            
            return $this->sendResponse(new CategoryResource($this->categoryService->find($id)), 'category detail edit');

        } catch(\Exception $e) {
            return $this->sendError($e->getMessage());
        }
    }

     /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        try {
            if(!$this->categoryService->find($id)) {
                return $this->sendError('category data not found', 404);
            }

            $category = $this->categoryService->update($request, $id);
            return $this->sendResponse(new CategoryResource($category), 'category updated successfully');

        } catch(\Exception $e) {
            return $this->sendError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            if(!$this->categoryService->find($id)) {
                return $this->sendError('category data not found', 404);
            }

            $this->categoryService->delete($id);
            return $this->sendResponse([], 'category deleted successfully');

        } catch(\Exception $e) {
            return $this->sendError($e->getMessage());
        }
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Requests\CategoryRequest;
use App\Services\Contracts\CategoryInterface as CategoryService;
use App\Notifications\CategoryStatusNotification;
class CategoryController extends Controller
{
    protected $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $categories = $this->categoryService->getAllPaginatedWithParams($request);
        return view('category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CategoryRequest $request)
    {
        try {
            $category = $this->categoryService->create($request);

            session()->flash('success', 'Category Created Successfully');
            return redirect()->route('categories.index');

        } catch(\Exception $e) {
            session()->flash('failed', $e->getMessage() . ' in file :'.$e->getFile() .' line: '. $e->getLine());
            return redirect()->back()->withInput($request->all());
        }
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $category = $this->categoryService->find($id);
        if(!$category) return abort('404', 'Category Not Found');

        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(CategoryRequest $request, $id)
    {
        try {
            $category = $this->categoryService->find($id);
            if(!$category) return abort('404', 'Category Not Found');

            $this->categoryService->update($request, $id);

            session()->flash('success', 'Category Updated Successfully');
            return redirect()->route('categories.index');

        } catch(\Exception $e) {
            session()->flash('failed', $e->getMessage() . ' in file :'.$e->getFile() .' line: '. $e->getLine());
            return redirect()->back()->withInput($request->all());
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        try {
            $category = $this->categoryService->find($id);
            if(!$category) return abort('404', 'Category Not Found');

            $this->categoryService->delete($id);

            session()->flash('success', 'Category Deleted Successfully');
            return redirect()->route('categories.index');

        } catch(\Exception $e) {
            session()->flash('failed', $e->getMessage() . ' in file :'.$e->getFile() .' line: '. $e->getLine());
            return redirect()->back();
        }
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="card border-0 shadow rounded">
                <div class="card-body">
                    @if(Session::has('failed'))
                        <p class="alert alert-danger">{{ Session::get('failed') }}</p>
                    @endif
                
                    <a href="{{ route('categories.create') }}" class="btn btn-md btn-success mb-3">Back</a>

                    <form action="{{ route('categories.store') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Name" value="{{ old('name') }}">
                            @error('name')
                                <span class="error invalid-feedback">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label>Status</label>
                            <select name="is_publish" class="form-control @error('is_publish') is-invalid @enderror">
                                <option value="">Status</option>
                                <option value="1" @selected(old('is_publish') == "1")>Published</option>
                                <option value="0" @selected(old('is_publish') == "0")>Not Published</option>
                            </select>
                            @error('is_publish')
                                <span class="error invalid-feedback">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="card border-0 shadow rounded">
                <div class="card-body">
                    @if(Session::has('failed'))
                        <p class="alert alert-danger">{{ Session::get('failed') }}</p>
                    @endif
                
                    <a href="{{ route('categories.create') }}" class="btn btn-md btn-success mb-3">Back</a>

                    <form action="{{ route('categories.update', $category->id) }}" method="POST">
                        @csrf
                        @method('PATCH')
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" placeholder="Name" value="{{ old('name', $category->name) }}">
                            @error('name')
                                <span class="error invalid-feedback">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <label>Status</label>
                            <select name="is_publish" class="form-control @error('is_publish') is-invalid @enderror">
                                <option value="">Status</option>
                                <option value="1" @selected($errors->any() ? (old('is_publish') == "1") : ($category->is_publish == "1"))>Published</option>
                                <option value="0" @selected($errors->any() ? (old('is_publish') == "0") : ($category->is_publish == "0"))>Not Published</option>
                            </select>
                            @error('is_publish')
                                <span class="error invalid-feedback">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="card border-0 shadow rounded">
                <div class="card-body">
                    @if(Session::has('failed'))
                        <p class="alert alert-danger">{{ Session::get('failed') }}</p>
                    @endif

                    @if(Session::has('success'))
                        <p class="alert alert-success">{{ Session::get('success') }}</p>
                    @endif

                    <a href="{{ route('categories.create') }}" class="btn btn-md btn-success mb-3">Add New</a>

                    <form class="form-inline float-right" method="GET" action="{{ route('categories.index') }}">
                        <div class="form-group">
                            <div class="input-group">
                                <input class="form-control" id="q" placeholder="" name="search" type="text" value="{{ request()->search }}" />
                                <button class="btn btn-primary btn-flat input-group-addon" type="submit">Search</button>
                            </div>
                        </div>
                    </form>
                    <br>
                    <table class="table table-bordered">
                        <thead>
                          <tr>
                            <th scope="col">No</th>
                            <th scope="col">Name</th>
                            <th scope="col">Is Publish</th>
                            <th scope="col">Created at</th>
                            <th scope="col">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                            @forelse ($categories as $key => $category)
                                <tr>
                                    <td class="text-center">
                                        {{ $categories->firstItem() + $key }}
                                    </td>
                                    <td>{{ $category->name }}</td>
                                    <td>{{ $category->is_publish == true ? 'Pusblihed' : 'Not Published' }}</td>
                                    <td>{{ $category->created_at }}</td>
                                    <td class="text-center">

                                        <form onsubmit="return confirm('Are you sure you want to delete data?');" action="{{ route('categories.destroy', $category->id) }}" method="POST">    
                                            <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-sm btn-primary">Edit</a>  
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <div class="alert alert-danger">
                                    Data Category Not Found.
                                </div>
                            @endforelse
                        </tbody>
                    </table>  
                    <div class="float-right">
                        {{ $categories->appends(['search' => Request::get('search')])->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection